content = {
    "bibtex_key": {"fi": "Avain", "en": "Key"},
    "title": {"fi": "Otsikko", "en": "Title"},
    "year": {"fi": "Julkaisuvuosi", "en": "Year"},
    "author": {"fi": "Kirjoittaja", "en": "Author"},
    "publisher": {"fi": "Julkaisija", "en": "Publisher"},
    "journal": {"fi": "Julkaisu", "en": "Journal"},
    "volume": {"fi": "Nide", "en": "Volume"},
    "number": {"fi": "Numero", "en": "Number"},
    "pages": {"fi": "Sivut", "en": "Pages"},
    "month": {"fi": "Kuukausi", "en": "Month"},
    "booktitle": {"fi": "Kirjan otsikko", "en": "Booktitle"},
    "editor": {"fi": "Editori", "en": "Editor"},
    "series": {"fi": "Sarja", "en": "Series"},
    "address": {"fi": "Osoite", "en": "Address"},
    "organization": {"fi": "Organisaatio", "en": "Organization"},
    "source_info": {"fi": "Lähteen tiedot", "en": "Source details"},
    "add_source": {"fi": "Lisää lähde", "en": "Add source"},
    "add_tag": {"fi": "Lisää tunniste", "en": "Add tag"},
    "add": {"fi": "Lisää", "en": "Add"},
    "name": {"fi": "Nimi", "en": "Name"},
    "page_title": {
        "fi": "BibTex -lähdehallintatyökalu",
        "en": "BibTex source management",
    },
    "article": {
        "fi": "Artikkeli",
        "en": "Article",
    },
    "book": {
        "fi": "Kirja",
        "en": "Book",
    },
    "inproceedings": {
        "fi": "Artikkeli conferenssijulkaisussa",
        "en": "Inproceedings",
    },
}
